import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export const Terms: React.FC = () => {
  return (
    <div className="flex-1 bg-canvas py-10 px-4">
      <div className="max-w-[640px] mx-auto bg-surface border border-slate-200 rounded-panel p-8 shadow-float">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-ink mb-6 transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to workspace</span>
        </Link>

        <h1 className="text-xl font-semibold text-ink mb-2">Terms and Conditions</h1>
        <p className="text-xs text-slate-500 mb-6 font-mono">Last updated: March 19, 2026</p>

        <div className="space-y-4 text-[15px] leading-relaxed text-slate-700">
          <section>
            <h2 className="text-base font-semibold text-ink mb-1">1. Advisory nature of scoring</h2>
            <p>
              The Site Readiness Score (0 to 100) and associated factor breakdowns generated by this tool are strictly
              advisory. They do not constitute certified engineering surveys, commercial appraisals, geotechnical
              assessments, or environmental impact certifications. All candidates require on-site physical diligence.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-1">2. Open data sources and as-is availability</h2>
            <p>
              This platform aggregates publicly available geospatial datasets including OpenStreetMap (licensed under
              the Open Data Commons Open Database License / ODbL), Census of India administrative units, Central Water
              Commission flood line contours, and regional electrical distribution maps. Data is provided as-is without
              express or implied warranties regarding completeness, timeliness, or positional accuracy.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-1">3. Source attribution</h2>
            <p>
              Users exporting reports or citing comparative analytics must preserve all dataset attributions.
              Cartographic materials derived from OpenStreetMap must visibly carry the attribution notice:
              <span className="font-mono text-xs block mt-1 bg-slate-100 p-2 rounded">
                © OpenStreetMap contributors, licensed under the Open Database License (ODbL).
              </span>
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-1">4. Limitation of liability</h2>
            <p>
              In no event shall the authors or project contributors be liable for any direct, indirect, incidental,
              or consequential damages arising out of the acquisition, leasing, or development of property based upon
              scores or metrics produced by this software.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-1">5. Governing law</h2>
            <p>
              This prototype is governed by the laws applicable to hackathon evaluations under Indian jurisdiction,
              without regard to conflict of law principles.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};
